services:
  db:
    image: mysql:8
    container_name: tellico_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tellico", "-ptellico"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  app:
    build: .
    container_name: tellico_back
    restart: always
    ports:
      - "${PORT}:3009"
    #command: ["./entrypoint.sh", "npm", "run", "start:dev"]  
    volumes:
      - ./src/:/code/src/
      - ./db:/code/db
      - ./package.json:/code/package.json
      - ./package-lock.json:/code/package-lock.json
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRESIN: ${JWT_ACCESS_EXPIRESIN}
      JWT_REFRESH_EXPIRESIN: ${JWT_REFRESH_EXPIRESIN}

volumes:
  db_data: {}  
