services:
  db:
    image: mysql:8
    container_name: tellico_mysql
    restart: always
    environment:
      MYSQL_DATABASE: tellico
      MYSQL_ROOT_PASSWORD: tellico
      MYSQL_USER: tellico
      MYSQL_PASSWORD: tellico
    ports:
      - "1000:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tellico", "-ptellico"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  app:
    build: .
    container_name: tellico_back
    restart: always
    ports:
      - "3009:3009"
    #command: ["./entrypoint.sh", "npm", "run", "start:dev"]        
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: tellico
      DB_PASSWORD: tellico
      DB_DATABASE: tellico
      JWT_ACCESS_SECRET: 9/qTecOdEhXncP1H6klVwDgYhe6v9e8nnGwoEJfiWCPEWEqWVh53YesPNinea2ysc5jxgM4LFSTj/5gUJniGhO/F46LM2F5aq8L89OEQiDyCxegNvzWg7Yiyf/wpicbEvYKdmmRqQX7qyoW18449M5fvuFt/Lzdy7LIQWR04OjdfchdcxhAf3595DrNjwbgT1QrI58XvBxbR88bbr9b6kxctu+5SeLMTdCiIjKmNBHN88sckWhKTbO1nVU2zNh9UlLLlR4aQhKiCHzmBAEVCYdDaM70huekxg9Gb9O9OGYvBoSd8feMTSNuhC56X6hYV9/Mtp2m5DME/V2jAdqi1OutAEhjMqn/Q==
      JWT_REFRESH_SECRET: wNKBZFGt9O/gemd6UkbeuYFvvdpWzQqsTnTR2HDPpREGJZH2gn1iOfL/uD/9Art5wVGn0S7Y7SiHMZ54oF9gvQX/m6EnxerqGBxSXRur6XLrNZPRzWCdE/5WwN2Pr/rFwWowcbPq4V/7WO2geLJ+IDftuq4I48x789Qh7Gb1gvjfchcfh/iuIIPBOrpQcQ8BKDe9PMsxcATyyMqokvHiV33n3J0k3G1GXj/hngFigHPZcF9GjVm0PQ31n3Q/7oZxsRpJJcjXcI5XGAQpqm8ZTzf680KUtni931BzBS7vE6Ka4/1suCjyM+PsUS/AHS9ra+3hDIc1b8GICjGsgjGrAig6NgR6wzg==
      JWT_ACCESS_EXPIRESIN: 60m
      JWT_REFRESH_EXPIRESIN: 131400m

volumes:
  db_data: {}  
